"""Tram Backend - Abstract Strategy Base Class.

All trading strategies inherit from BaseStrategy and implement the `evaluate`
method. The scanner engine calls evaluate() on every closed candle, and the
strategy returns a SignalProposal if conditions are met.

Design:
    - Strategies are pure signal generators — no execution logic
    - Each strategy declares its required parameters and timeframe
    - SignalProposal is a lightweight data class that the engine converts
      to a persistent Signal record
    - Strategies have access to indicators via IndicatorResult
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any

from app.scanner.candle_buffer import CandleBuffer, IndicatorResult


@dataclass(frozen=True)
class SignalProposal:
    """A proposed signal generated by a strategy.

    This is the output of strategy.evaluate(). The scanner engine decides
    whether to persist it as a Signal record.
    """

    symbol: str
    timeframe: str
    direction: str  # "long" or "short"
    entry_price: float
    stop_loss: float
    take_profit: float
    confidence: float  # 0-100
    metadata: dict = field(default_factory=dict)

    @property
    def risk_reward(self) -> float:
        """Calculate risk/reward ratio."""
        if self.entry_price == self.stop_loss:
            return 0.0
        if self.direction == "long":
            risk = self.entry_price - self.stop_loss
            reward = self.take_profit - self.entry_price
        else:
            risk = self.stop_loss - self.entry_price
            reward = self.entry_price - self.take_profit

        return reward / risk if risk > 0 else 0.0


class BaseStrategy(ABC):
    """Abstract base class for all trading strategies.

    Subclasses must implement:
        - name: unique strategy identifier (matches DB strategies.name)
        - evaluate(): analyze indicators and return a SignalProposal or None

    Strategies should be stateless between calls — all state lives in the
    CandleBuffer/IndicatorResult. This makes strategies easy to test.
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """Unique name matching the `strategies` table entry."""
        ...

    @property
    @abstractmethod
    def description(self) -> str:
        """Human-readable description of the strategy."""
        ...

    @property
    @abstractmethod
    def default_timeframe(self) -> str:
        """Primary timeframe this strategy operates on."""
        ...

    @property
    @abstractmethod
    def default_parameters(self) -> dict[str, Any]:
        """Default configuration parameters."""
        ...

    def __init__(self, parameters: dict[str, Any] | None = None):
        """Initialize with optional parameter overrides."""
        self.parameters = {**self.default_parameters}
        if parameters:
            self.parameters.update(parameters)

    def get_param(self, key: str, default: Any = None) -> Any:
        """Get a parameter value with optional default."""
        return self.parameters.get(key, default)

    @abstractmethod
    def evaluate(
        self,
        buffer: CandleBuffer,
        indicators: IndicatorResult,
    ) -> SignalProposal | None:
        """Evaluate current market conditions and optionally propose a signal.

        Args:
            buffer: The candle buffer for this symbol/timeframe
            indicators: Pre-computed indicator values

        Returns:
            SignalProposal if conditions are met, None otherwise
        """
        ...

    def compute_indicators(self, buffer: CandleBuffer) -> IndicatorResult:
        """Compute indicators using strategy-specific parameters.

        Override in subclasses that need custom indicator parameters.
        """
        return buffer.compute_indicators()

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(name={self.name!r}, params={self.parameters})"
